definitions:
  dto.DefaultResponse:
    properties:
      message:
        type: string
    type: object
  dto.LoginResponse:
    properties:
      accessToken:
        type: string
      idToken:
        type: string
      refreshToken:
        type: string
      tokenType:
        type: string
    type: object
  dto.RefreshTokenResponse:
    properties:
      accessToken:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/auth/create-account/:
    post:
      consumes:
      - application/json
      description: save user details to database
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Create user account for admin
      tags:
      - auth
  /admin/auth/login/:
    post:
      consumes:
      - application/json
      description: Validate Admin credentials, authenticate and authorize with JWT
        provision
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Enable sign in and authorization for Admin with valid credentials
      tags:
      - auth
  /admin/auth/login/send-otp:
    post:
      consumes:
      - application/json
      description: Send OTP to specified admin email address for authentication
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: initiate email validation for admin login concurrency
      tags:
      - auth
  /admin/auth/login/verify:
    post:
      consumes:
      - application/json
      description: validate OTP to specified admin email address for authentication
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Enable admin login concurrency via otp confirmation
      tags:
      - auth
  /admin/auth/logout/:
    delete:
      consumes:
      - application/json
      description: Log patient out with server wipe of session data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Enable sign out and session delete for admin with valid credentials
      tags:
      - auth
  /admin/auth/refresh/:
    get:
      consumes:
      - application/json
      description: Create New Access Token for Admin Authentication with Refresh Token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RefreshTokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Refresh Expired Access Token
      tags:
      - auth
  /patient/auth/email/send-otp:
    post:
      consumes:
      - application/json
      description: Send OTP to specified patient email address for new account registration
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: initiate email validation for patient sign up
      tags:
      - auth
  /patient/auth/email/verify:
    post:
      consumes:
      - application/json
      description: Verify OTP sent to specified patient email address for new account
        registration
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Enable patient sign up via email validation with OTP
      tags:
      - auth
  /patient/auth/login/:
    post:
      consumes:
      - application/json
      description: Validate patient credentials, authenticate and authorize with JWT
        provision
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Enable sign in and authorization for patient with valid credentials
      tags:
      - auth
  /patient/auth/logout/:
    delete:
      consumes:
      - application/json
      description: Log patient out with server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Enable sign out for patient with valid credentials
      tags:
      - auth
  /patient/auth/refresh/:
    get:
      consumes:
      - application/json
      description: Create New Access Token for Patient Authentication with Refresh
        Token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RefreshTokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Refresh Expired Access Token
      tags:
      - auth
  /patient/auth/register/:
    post:
      consumes:
      - application/json
      description: save user details to database
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.DefaultResponse'
      summary: Create user account for patient
      tags:
      - auth
swagger: "2.0"
