definitions:
  auth.DefaultResponse:
    properties:
      message:
        type: string
    type: object
  auth.LoginResponse:
    properties:
      accessToken:
        type: string
      idToken:
        type: string
      refreshToken:
        type: string
      tokenType:
        type: string
    type: object
info:
  contact: {}
paths:
  /patient/auth/confirm-email/process/:
    post:
      consumes:
      - application/json
      description: Send OTP to specified patient email address for authentication
        and registration
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
      summary: initiate email validation for patient sign up or login concurrency
      tags:
      - auth
  /patient/auth/login/:
    post:
      consumes:
      - application/json
      description: Validate patient credentials, authenticate and authorize with JWT
        provision
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
      summary: Enable sign in and authorization for patient with valid credentials
      tags:
      - auth
  /patient/auth/logout/:
    delete:
      consumes:
      - application/json
      description: Log patient out with server wipe of session data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
      summary: Enable sign out and session delete for patient with valid credentials
      tags:
      - auth
  /patient/auth/register/:
    post:
      consumes:
      - application/json
      description: save user details to database
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
      summary: Create user account for patient
      tags:
      - auth
  /patient/auth/verify-otp/process/:
    post:
      consumes:
      - application/json
      description: validate OTP to specified patient email address for authentication
        and registration
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/auth.DefaultResponse'
      summary: Enable patient sign up or login concurrency via validation
      tags:
      - auth
swagger: "2.0"
